chunkDir: tmp/chunks
dbPath: tmp/state.db
streams:
  # - id: triplej
  #   name: Triple J
  #   url: https://abcradiolivehls-lh.akamaihd.net/i/triplejnsw_1@327300/index_64_a-p.m3u8?sd=10&rebase=on
  #   baseTimezone: Australia/Sydney
  - id: doublej
    name: Double J
    url: https://abcradiolivehls-lh.akamaihd.net/i/doublejnsw_1@327293/index_64_a-p.m3u8?sd=10&rebase=on
    baseTimezone: Australia/Sydney
