chunkDir: tmp/chunks
dbPath: tmp/state.db
streams:
  # - id: triplej
  #   name: Triple J
  #   url: https://mediaserviceslive.akamaized.net/hls/live/2038308/triplejnsw/masterhq.m3u8
  #   baseTimezone: Australia/Sydney
  #   nowPlayingURL: https://music.abcradio.net.au/api/v1/plays/triplej/now.json
  - id: doublej
    name: Double J
    url: https://mediaserviceslive.akamaized.net/hls/live/2038315-b/doublejnsw/masterhq.m3u8
    baseTimezone: Australia/Sydney
    nowPlayingURL: https://music.abcradio.net.au/api/v1/plays/doublej/now.json
